Replace redundant version renaming with filename check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -73,20 +73,29 @@ jobs:
       - name: Ensure executable permissions
         run: chmod a+x ./tableau-connector/build.sh
 
-      - name: Assemble Tableau Connector
-        run: ./tableau-connector/build.sh
-
-      - name: View assembled file
-        run: ls -l tableau-connector/target
-
-      - name: Add version to TACO file
+      - name: Get driver version
         run: |
           file="./gradle.properties"
           MAJOR_VERSION=$(grep "MAJOR_VERSION" ${file} | cut -d'=' -f2)
           MINOR_VERSION=$(grep "MINOR_VERSION" ${file} | cut -d'=' -f2)
           PATCH_VERSION=$(grep "PATCH_VERSION" ${file} | cut -d'=' -f2)
           echo "version=$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION" >> $GITHUB_ENV
-          mv  tableau-connector/target/neptune-jdbc.taco tableau-connector/target/neptune-jdbc-$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.taco
+
+      - name: Assemble Tableau Connector
+        run: ./tableau-connector/build.sh ${{env.version}}
+
+      - name: View assembled file
+        run: ls -l tableau-connector/target
+
+      - name: Verify TACO filename
+        run: |
+          if [ ! -f "tableau-connector/target/neptune-jdbc-v${{env.version}}.taco" ]
+          then
+            echo "Error: The TACO file is either incorrectly named or missing from tableau-connector/target/."
+            echo "Contents of tableau-connector/target/:"
+            ls tableau-connector/target
+            exit 1
+          fi
 
       - name: "Configure AWS credentials"
         if: ${{env.SIGNING_ENABLED == 'true'}}
